# Generated by Django 5.2.4 on 2025-07-29 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_section_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='course',
        ),
        migrations.RemoveField(
            model_name='section',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
